services:
  api:
    image: ghcr.io/horny-pony-studio/srochno-backend:${TAG:-latest}
    ports:
      - "20001:8000"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
